/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _1_hello_world_c_1_opaque_NodeStruct ;
struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
typedef struct _1_hello_world_c_1_opaque_NodeStruct *_1_hello_world_c_1_opaque_StructureType;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   *format  , ...) ;
struct _1_hello_world_c_1_opaque_NodeStruct {
   struct _1_hello_world_c_1_opaque_NodeStruct *prev ;
   int data ;
   struct _1_hello_world_c_1_opaque_NodeStruct *next ;
};
struct _1_hello_world_c_1_opaque_NodeStruct *_1_hello_world_c_1_opaque_list_1  =    (struct _1_hello_world_c_1_opaque_NodeStruct *)0;
extern int pthread_cond_signal(int *cond ) ;
extern int raise(int sig ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int scanf(char const   *format  , ...) ;
extern int unlink(char const   *filename ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
void main(void) ;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
struct _1_hello_world_c_1_opaque_NodeStruct *_1_hello_world_c_1_opaque_ptr_2  =    (struct _1_hello_world_c_1_opaque_NodeStruct *)0;
extern double ceil(double x ) ;
void hello_world_c(void) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
struct _1_hello_world_c_1_opaque_NodeStruct *_1_hello_world_c_1_opaque_ptr_1  =    (struct _1_hello_world_c_1_opaque_NodeStruct *)0;
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   int tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern double sqrt(double x ) ;
extern void *malloc(unsigned int size ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
void megaInit(void) ;
struct _1_hello_world_c_1_opaque_NodeStruct *_1_hello_world_c_1_opaque_list_2  =    (struct _1_hello_world_c_1_opaque_NodeStruct *)0;
void hello_world_c(void) 
{ 
  struct _1_hello_world_c_1_opaque_NodeStruct *p1 ;
  int r2 ;
  struct _1_hello_world_c_1_opaque_NodeStruct *p3 ;
  int r4 ;
  struct _1_hello_world_c_1_opaque_NodeStruct *p5 ;
  int _1_hello_world_c__BEGIN_0 ;
  int _1_hello_world_c__END_0 ;
  int _1_hello_world_c__BARRIER_1 ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _1_hello_world_c__BEGIN_0 = 1;
  p1 = (struct _1_hello_world_c_1_opaque_NodeStruct *)malloc(sizeof(struct _1_hello_world_c_1_opaque_NodeStruct ));
  p1->next = p1;
  p1->prev = p1;
  _1_hello_world_c_1_opaque_list_1 = p1;
  r4 = rand();
  p5 = (struct _1_hello_world_c_1_opaque_NodeStruct *)malloc(sizeof(struct _1_hello_world_c_1_opaque_NodeStruct ));
  p5->data = 0 * r4;
  p5->next = _1_hello_world_c_1_opaque_list_1->next;
  p5->prev = _1_hello_world_c_1_opaque_list_1;
  (_1_hello_world_c_1_opaque_list_1->next)->prev = p5;
  _1_hello_world_c_1_opaque_list_1->next = p5;
  r2 = rand();
  p3 = (struct _1_hello_world_c_1_opaque_NodeStruct *)malloc(sizeof(struct _1_hello_world_c_1_opaque_NodeStruct ));
  p3->data = 1 * r2;
  p3->next = _1_hello_world_c_1_opaque_list_1->next;
  p3->prev = _1_hello_world_c_1_opaque_list_1;
  (_1_hello_world_c_1_opaque_list_1->next)->prev = p3;
  _1_hello_world_c_1_opaque_list_1->next = p3;
  _1_hello_world_c_1_opaque_ptr_1 = _1_hello_world_c_1_opaque_list_1->next;
  _1_hello_world_c_1_opaque_ptr_2 = _1_hello_world_c_1_opaque_ptr_1;
  _1_hello_world_c__END_0 = 1;
  }
  _1_hello_world_c__BARRIER_1 = 1;

  if (_1_hello_world_c_1_opaque_ptr_1 == _1_hello_world_c_1_opaque_ptr_2) {

  } else {
    hello_world_c();
  }
  if (_1_hello_world_c_1_opaque_ptr_1 != _1_hello_world_c_1_opaque_ptr_2) {
    {
    if (_1_hello_world_c_1_opaque_ptr_1 == _1_hello_world_c_1_opaque_ptr_2) {

    } else {
      hello_world_c();
    }
    if (_1_hello_world_c_1_opaque_ptr_1 != _1_hello_world_c_1_opaque_ptr_2) {
      hello_world_c();
    } else {

    }
    }
    if (_1_hello_world_c_1_opaque_ptr_1 != _1_hello_world_c_1_opaque_ptr_2) {
      hello_world_c();
    } else {

    }
    hello_world_c();
  } else {

  }
  return;
}
}
